apiVersion: v1
kind: PersistentVolume
metadata:
 name: valheim-data
 labels:
  type: local
spec:
 storageClassName: manual
 capacity:
  storage: 50Gi
 accessModes:
  - ReadWriteOnce
 hostPath:
  path: "/home/vox/valheim-data"
