apiVersion: v1
kind: Service
metadata:
 name: valheim-server
spec:
 ports:
  - name: gameport
    nodePort: 31000
    port: 2456
    targetPort: 2456
    protocol: UDP

  - name: queryport
    nodePort: 31001
    port: 2457
    targetPort: 2457
    protocol: UDP

 type: LoadBalancer
 selector:
  app: valheim-server
